New entry event
wpwhitesecurity/wsal-wpforms pull request #115
Opened 2022-02-16 19:02 UTC by DannyWPWS

2022-02-16 19:11 UTC, DannyWPWS commented
Marking as not ready as it needs to go in after this one :) https://github.com/wpwhitesecurity/wsal-wpforms/pull/114

2022-02-18 07:05 UTC, martinkrcho commented on wp-security-audit-log/custom-sensors/WPFormsSensor.php
> +	function event_entry_added( $fields, $entry, $form_data, $entry_id ) {
Let's add some phpdoc for this function, please.

2022-02-18 07:07 UTC, martinkrcho requested changes
Overall changes look OK. Please see my comments. Only minor stuff again. Is the code passing the coding standards check for you? Couple of things should definitely fail.

2022-02-22 07:29 UTC, martinkrcho approved these changes
All changes are looking good now.

2022-02-22 07:31 UTC, merged